# Generated by Django 4.2.2 on 2023-06-15 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destinazione',
            fields=[
                ('destinazione_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descrizione', models.TextField()),
                ('paese', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Struttura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descrizione', models.TextField()),
                ('indirizzo', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('destinazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.destinazione')),
            ],
        ),
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('nome_completo', models.CharField(max_length=100, null=True)),
                ('prenotazione_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('data_inizio', models.DateField()),
                ('data_fine', models.DateField()),
                ('numero_persone', models.PositiveIntegerField()),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('destinazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.destinazione')),
            ],
        ),
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100)),
                ('descrizione', models.TextField()),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('day1', models.CharField(blank=True, max_length=200, null=True)),
                ('day2', models.CharField(blank=True, max_length=200, null=True)),
                ('day3', models.CharField(blank=True, max_length=200, null=True)),
                ('day4', models.CharField(blank=True, max_length=200, null=True)),
                ('day5', models.CharField(blank=True, max_length=200, null=True)),
                ('day6', models.CharField(blank=True, max_length=200, null=True)),
                ('day7', models.CharField(blank=True, max_length=200, null=True)),
                ('destinazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.destinazione')),
            ],
        ),
    ]
